#!/usr/bin/env bash
# ════════════════════════════════════════════════════════════════════
# apply-tuning.sh — standalone tuner for a VPN/Linux node.
#
# Applies ALL recommended optimizations without running a diagnosis first:
#   • sysctl: BBR + cake, buffers, tcp_mtu_probing, fastopen, conntrack
#   • iptables MSS clamp (clamp-mss-to-pmtu) on FORWARD/OUTPUT
#   • RPS — spread softirq across all CPUs (persisted via systemd)
#   • NIC ring buffers raised to maximum (persisted via systemd)
#   • vm.swappiness = 10
#
# Companion to node-diagnostic.sh — uses the same paths, systemd units,
# backup dir and journal, so `revert-tuning.sh` can undo it.
#
#   sudo bash apply-tuning.sh            # apply everything
#   sudo bash apply-tuning.sh --dry-run  # show what would change
#   sudo bash apply-tuning.sh -i eth0    # force a specific interface
# ════════════════════════════════════════════════════════════════════
set -u

# ── colors ──────────────────────────────────────────────────────────
if [ -t 1 ]; then
    R=$'\033[0;31m'; G=$'\033[0;32m'; Y=$'\033[1;33m'; C=$'\033[0;36m'
    BOLD=$'\033[1m'; DIM=$'\033[2m'; NC=$'\033[0m'
else
    R=""; G=""; Y=""; C=""; BOLD=""; DIM=""; NC=""
fi

have() { command -v "$1" >/dev/null 2>&1; }

DRY_RUN=0
IFACE=""
while [ $# -gt 0 ]; do
    case "$1" in
        --dry-run)   DRY_RUN=1 ;;
        -i|--iface)  IFACE="$2"; shift ;;
        -h|--help)
            grep -E '^#( |$)' "$0" | sed 's/^# \{0,1\}//'
            exit 0 ;;
        *) echo "unknown option: $1" >&2; exit 1 ;;
    esac
    shift
done

if [ "$EUID" -ne 0 ] && [ "$DRY_RUN" = "0" ]; then
    echo -e "${R}✗${NC} Root required. Re-run under sudo (or use --dry-run)."
    exit 1
fi

[ -z "$IFACE" ] && IFACE=$(ip -4 route show default 2>/dev/null | awk '/default/ {print $5; exit}')

FIX_LOG="/etc/node-diagnostic.applied"
BACKUP_DIR="/var/backups/node-diagnostic"
BACKUP_TS=""

run_or_dry() {
    if [ "$DRY_RUN" = "1" ]; then
        echo -e "    ${DIM}[dry-run]${NC} $*"
        return 0
    fi
    eval "$@"
}

record_fix() {
    [ "$DRY_RUN" = "1" ] && return
    printf '%s | %s\n' "$(date -u +'%Y-%m-%dT%H:%M:%SZ')" "$1" >> "$FIX_LOG" 2>/dev/null || true
}

backup_settings() {
    [ "$DRY_RUN" = "1" ] && return
    [ -n "$BACKUP_TS" ] && return
    mkdir -p "$BACKUP_DIR" 2>/dev/null || return
    BACKUP_TS=$(date +%Y%m%d-%H%M%S)
    sysctl -a 2>/dev/null > "$BACKUP_DIR/sysctl-$BACKUP_TS.txt"
    have iptables-save  && iptables-save  > "$BACKUP_DIR/iptables-$BACKUP_TS.rules"  2>/dev/null
    have ip6tables-save && ip6tables-save > "$BACKUP_DIR/ip6tables-$BACKUP_TS.rules" 2>/dev/null
    echo -e "    ${DIM}backup: $BACKUP_DIR/*-$BACKUP_TS.* — for rollback${NC}"
    record_fix "backup snapshot $BACKUP_TS"
}

# ── fixes ───────────────────────────────────────────────────────────
fix_sysctl() {
    backup_settings
    local target=/etc/sysctl.d/99-vpn-tuning.conf
    echo -e "  ${C}→${NC} writing $target"
    if [ "$DRY_RUN" = "1" ]; then
        echo -e "    ${DIM}[dry-run]${NC} (BBR/cake/buffers/tcp_mtu_probing/conntrack)"
        return
    fi
    cat > "$target" <<'SYSCTL_EOF'
# Generated by apply-tuning.sh (node-diagnostic)
# Congestion + qdisc
net.core.default_qdisc = cake
net.ipv4.tcp_congestion_control = bbr
# PMTU & idle
net.ipv4.tcp_mtu_probing = 1
net.ipv4.tcp_slow_start_after_idle = 0
net.ipv4.tcp_notsent_lowat = 131072
net.ipv4.tcp_fastopen = 3
# Buffers
net.core.rmem_max = 67108864
net.core.wmem_max = 67108864
net.ipv4.tcp_rmem = 4096 87380 67108864
net.ipv4.tcp_wmem = 4096 65536 67108864
# Queues
net.core.netdev_max_backlog = 16384
net.core.somaxconn = 8192
net.ipv4.tcp_max_syn_backlog = 8192
# Conntrack
net.netfilter.nf_conntrack_max = 524288
SYSCTL_EOF
    sysctl --system >/dev/null 2>&1 \
        && echo -e "    ${G}✓${NC} sysctl --system applied" \
        || echo -e "    ${R}✗${NC} sysctl --system returned an error"
    record_fix "sysctl tuning ($target)"
}

fix_mss_clamp() {
    have iptables || { echo -e "  ${Y}⚠${NC} iptables not installed — skipping MSS clamp"; return; }
    backup_settings
    local rule_args=(-p tcp --tcp-flags SYN,RST SYN -j TCPMSS --clamp-mss-to-pmtu)
    echo -e "  ${C}→${NC} iptables MSS clamp on FORWARD/OUTPUT"
    for chain in FORWARD OUTPUT; do
        if iptables -t mangle -C "$chain" "${rule_args[@]}" 2>/dev/null; then
            echo -e "    ${DIM}rule already present in $chain${NC}"
        else
            run_or_dry "iptables -t mangle -A $chain ${rule_args[*]}" \
                && echo -e "    ${G}✓${NC} $chain"
        fi
    done
    if [ "$DRY_RUN" = "0" ]; then
        if have netfilter-persistent; then
            netfilter-persistent save >/dev/null 2>&1 \
                && echo -e "    ${G}✓${NC} netfilter-persistent save"
        elif [ -d /etc/iptables ] && have iptables-save; then
            iptables-save > /etc/iptables/rules.v4 \
                && echo -e "    ${G}✓${NC} saved to /etc/iptables/rules.v4"
        else
            echo -e "    ${Y}⚠${NC} no netfilter-persistent — rules will NOT survive a reboot (apt install iptables-persistent)"
        fi
        record_fix "iptables MSS clamp (FORWARD+OUTPUT)"
    fi
}

fix_rps() {
    local iface=$1
    [ -z "$iface" ] && { echo -e "  ${R}✗${NC} interface not determined — skipping RPS"; return 1; }
    local n mask applied=0
    n=$(nproc)
    mask=$(printf '%x' $(( (1 << n) - 1 )))
    echo -e "  ${C}→${NC} RPS mask=$mask on $iface"
    for q in /sys/class/net/"$iface"/queues/rx-*; do
        [ -d "$q" ] || continue
        if [ "$DRY_RUN" = "1" ]; then
            echo -e "    ${DIM}[dry-run]${NC} echo $mask > $q/rps_cpus"
        else
            echo "$mask" > "$q/rps_cpus" 2>/dev/null && applied=$((applied+1))
        fi
    done
    [ "$DRY_RUN" = "0" ] && echo -e "    ${G}✓${NC} applied to $applied queues"
    [ "$DRY_RUN" = "1" ] && return
    cat > /etc/systemd/system/vpn-rps.service <<UNIT
[Unit]
Description=Apply RPS mask for $iface
After=network-online.target

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/bin/bash -c 'for q in /sys/class/net/$iface/queues/rx-*; do echo $mask > \$q/rps_cpus; done'

[Install]
WantedBy=multi-user.target
UNIT
    systemctl daemon-reload
    systemctl enable --now vpn-rps.service >/dev/null 2>&1 \
        && echo -e "    ${G}✓${NC} systemd unit vpn-rps.service created and enabled"
    record_fix "RPS mask=$mask on $iface (vpn-rps.service)"
}

fix_ring_buffers() {
    local iface=$1
    [ -z "$iface" ] && { echo -e "  ${R}✗${NC} interface not determined — skipping ring buffers"; return; }
    have ethtool || { echo -e "  ${Y}⚠${NC} ethtool not installed — skipping ring buffers"; return; }
    local max_rx max_tx cur_rx cur_tx
    max_rx=$(ethtool -g "$iface" 2>/dev/null | awk '/Pre-set maximums/,/Current/' | awk '/RX:/ {print $2; exit}')
    max_tx=$(ethtool -g "$iface" 2>/dev/null | awk '/Pre-set maximums/,/Current/' | awk '/TX:/ {print $2; exit}')
    cur_rx=$(ethtool -g "$iface" 2>/dev/null | awk '/Current hardware settings/,0' | awk '/RX:/ {print $2; exit}')
    cur_tx=$(ethtool -g "$iface" 2>/dev/null | awk '/Current hardware settings/,0' | awk '/TX:/ {print $2; exit}')
    echo -e "  ${C}→${NC} ring buffers: max RX=$max_rx TX=$max_tx (current $cur_rx/$cur_tx)"
    if [ -z "$max_rx" ] || [ "$max_rx" = "0" ]; then
        echo -e "    ${Y}⚠${NC} NIC doesn't support changing ring buffers (often virtio_net)"
        return
    fi
    if [ "$cur_rx" = "$max_rx" ] && [ "$cur_tx" = "$max_tx" ]; then
        echo -e "    ${DIM}already at maximum${NC}"
        return
    fi
    run_or_dry "ethtool -G $iface rx $max_rx tx $max_tx" && echo -e "    ${G}✓${NC} applied"
    [ "$DRY_RUN" = "1" ] && return
    cat > /etc/systemd/system/vpn-ring.service <<UNIT
[Unit]
Description=Apply NIC ring buffers for $iface
After=network-online.target

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/sbin/ethtool -G $iface rx $max_rx tx $max_tx

[Install]
WantedBy=multi-user.target
UNIT
    systemctl daemon-reload
    systemctl enable --now vpn-ring.service >/dev/null 2>&1 \
        && echo -e "    ${G}✓${NC} systemd unit vpn-ring.service created and enabled"
    record_fix "ring buffers RX=$max_rx TX=$max_tx on $iface (vpn-ring.service)"
}

fix_swappiness() {
    echo -e "  ${C}→${NC} vm.swappiness = 10"
    [ "$DRY_RUN" = "1" ] && { echo -e "    ${DIM}[dry-run]${NC} write /etc/sysctl.d/98-swappiness.conf"; return; }
    echo "vm.swappiness = 10" > /etc/sysctl.d/98-swappiness.conf
    sysctl -p /etc/sysctl.d/98-swappiness.conf >/dev/null 2>&1 && echo -e "    ${G}✓${NC} applied"
    record_fix "vm.swappiness=10"
}

# ── run ─────────────────────────────────────────────────────────────
echo
echo -e "${BOLD}  Node tuning — applying all optimizations${NC}"
[ "$DRY_RUN" = "1" ] && echo -e "${DIM}  (dry-run — nothing will be changed)${NC}"
echo -e "${DIM}  interface: ${IFACE:-<none>}${NC}"
echo

fix_sysctl
fix_mss_clamp
fix_rps          "$IFACE"
fix_ring_buffers "$IFACE"
fix_swappiness

echo
if [ "$DRY_RUN" = "1" ]; then
    echo -e "  ${DIM}Dry-run done. Re-run without --dry-run to apply.${NC}"
else
    echo -e "  ${G}${BOLD}✓ Done.${NC} ${DIM}Journal: $FIX_LOG · backup: $BACKUP_DIR${NC}"
    echo -e "  ${DIM}Revert with: sudo bash revert-tuning.sh${NC}"
fi
echo
